### ISSUE TITLE
Use issues for ideas/discussion

### ISSUE THREAD

**Issue by mjcarroll** [Code4Huntsville/projects_leader_board#1]
Perhaps following this: https://www.youtube.com/watch?v=KlrJVSJRUN4
or this: https://github.com/openoakland/ideas

We can discuss more at the meeting tonight, but github issues have a few advantages:
- They have an API
- They have an iphone app
- They have a lower learning curve than editing a git repo.

**Comment by mjcarroll** [comment]
Like this: https://github.com/openoakland/ideas

**Comment by glmason** [comment]
Yes... I like the idea of using issues for ideas... Will transfer (as examples) the four ideas that I have on the project leader board.

**Comment by larrymason** [comment]
Oops was signed in under a different account... Will put a link to the issues section on the web site, as a place to submit ideas.

**Comment by mjcarroll** [comment]
During my discussion with Neil and Chris last night, it came up that GitHub may have too step a learning curve for non-technical users to submit ideas.

It was suggested that a google form be used instead.  For now, we can have someone hand transfer from the google doc to the ideas repo issues page, but it could be automated in the future.

~mc mobile

**Comment by mjcarroll** [comment]
:+1: Larry got it.
