### ISSUE TITLE
Frontier App: Enter your address, get text about local community resources

### ISSUE THREAD

**Issue by chrisbeaman** [Code4Huntsville/projects_leader_board#12]
Per Madhav's original idea, let's build a web app where we let users input their address and then generate a text-based list of community resources that are accessible to them. This tool would be handy to someone looking to travel or move to Huntsville. 

Examples: 
1. Your trash collection day is Wednesday.
2. Your recycling collection day is Thursday.
3. The closest elementary school to you is Mary Smith Elementary.

Competitors/Existing solutions:
None of the existing solutions I found offer a solution that replicates this idea. These solutions are similar, but often map-based and over-complicated.
- City Data: http://www.city-data.com/zips/35758.html
- Trulia: http://www.trulia.com/local/35758/unrated:1%7Cdistrict:1%7Celementary:1%7Cmiddle:1%7Chigh:1%7Crating:1_schools
- ZipWho: http://zipwho.com/?zip=35758&city=&filters=--_--_--_--&state=&mode=zip
- WalkScore: https://www.walkscore.com/AL/Madison/35758
- GreatSchools: http://www.greatschools.org/search/search.page?lat=34.7091114&lon=-86.7617490&zipCode=35758&state=AL&locationType=postal_code&normalizedAddress=Madison%2C%20AL%2035758&city=Madison&sortBy=DISTANCE&locationSearchString=35758&distance=5
- Moving: http://www.moving.com/real-estate/city-profile/results.asp?Zip=35758
- Neighborhood Scout: http://www.neighborhoodscout.com/al/madison/city-center/#demographics

Whiteboarding:
Here are some screenshots of some whiteboard exercises Chris and J Langley worked on:
- Layers: http://i.imgur.com/XBP3Wc0.jpg
- Wireframe: http://i.imgur.com/ZnMDCOY.jpg
- User Stories: http://i.imgur.com/tirSIoK.jpg

Layers:
There are a bunch of layers shown in the Layers screenshot above, but here are a few extras suggested by J Langley's wife :)
- Bakeries
- Farmers Markets
- Liquor store
- Dry cleaners and laundromat
- Bank / ATM
- Transportation rental and taxi

**Comment by spearna** [comment]
:+1:

**Comment by dannagle** [comment]
1. Your broadband Internet choices are AT&T for DSL, Comcast for cable, etc. 
2. Your network television providers are WoW, DirectTV, AT&T Uverse, etc.
3. Here are links to coverage maps from Verizon, AT&T, T-Mobile, etc.  
4. The closet city bus stop is X miles away, and it is at Y.

**Comment by Nedlinin** [comment]
Where would we source this data from?  Does anyone know of publicly accessible APIs for all of this?  Or are we hoping for users to fill in the information for us and we keep our own database?

**Comment by mjcarroll** [comment]
Most of the data in here is available in formats of our choosing according to City GIS: http://maps.huntsvilleal.gov/public/ I believe that these datasets are NONCOMMERCIAL.

It includes:
- School districts
- Voting districts
- Trash/city maintenance districts ( http://maps.huntsvilleal.gov/SanitationRoutes/ )
- Police districts

**Comment by PaigeColburn** [comment]
This sounds like a great project! I'm excited to see it come to fruition. 

Other Code4 Brigades have encountered a problem after making apps like this one for their cities: 

Sustainability- the project generates a lot of excitement initially and work accelerates until it is completed. Then the "maintenance" phase falls flat. If the public latches on to an app you produce for the City, like this one, the public will expect maintenance and continued accuracy for years to come. 

Just an FYI as you guys get started on your first big projects for Huntsville. We don't want the public to be disappointed a year from now with inaccurate information on this or any of the tools you make for our citizens. 

THANK YOU!! This is very exciting. I can't wait to try it out myself. 
- Paige

**Comment by akenum** [comment]
Here is the a non-map version of the quick address search that Huntsville GIS maintains.
http://maps.hsvcity.com/address/
Search by address and it lists these items.

308 FOUNTAIN CIR SW
Mailing Address
308 FOUNTAIN CIR SW
HUNTSVILLE AL 35801

City Council
DISTRICT 1 – RICHARD SHOWERS, SR

School Board
DISTRICT 1 – LAURIE MCCAULLEY

School Zones
BLOSSOMWOOD ELEMENTARY SCHOOL
HUNTSVILLE MIDDLE SCHOOL
HUNTSVILLE HIGH SCHOOL

Recreation
ZONE 3
METRO LEAGUE

Zoning
C3 – GENERAL BUSINESS C-3

Sanitation Route
ROUTE 6A – MONDAY COLLECTION

SWDA Recycling Service
THURSDAY COLLECTION

County
MADISON COUNTY

County Commission
DISTRICT 1 – ROGER JONES

Census Tract
31

**Comment by PaigeColburn** [comment]
I tried to search my address and twice it wouldn't find it. So I used the "Select Street" pull-down option. The problem was I put the full word "Circle" in my street address, whereas this database lists my street as "CIR" and will accept no substitutes. 

Just fixing a little thing like that- so when someone types "Circle" the tool looks for all variants or abbreviations- would be super helpful. 

As you guys create your app version of this, keep that in mind, please. 
- Paige

**Comment by chrisbeaman** [comment]
Comment from Kyle: 

Sketch: http://i.imgur.com/7U7RZho.jpg

From what I heard about the direction of the app - discovery of things based on categories, I had an idea for the UX. I'm not married to it, but maybe it will help some creativity for you.

I was thinking it might be cool to borrow from http://songza.com/.

For example, if I'm hungry, I might want to know the closest food truck,  local restaurant, coffee shop, bar, fast food, etc. or just the closest restaurants (period).

Other categories I heard (with crossover):
Work (wifi, coworking spaces)
Play (swing dance, art gallery)
Travel (gas, bus)
Eat (above)
Recreate actively (parks, trails)
Time-sensitive (voting, big city events)

**Comment by chrisbeaman** [comment]
Comment from James: 

Last night two issues were mentioned but not resolved:
- What could this application do that other services do not?
- I think people were inadvertently trying to communicate "Who would use this application if they are already familiar with the city and they know what they are looking for?".

I propose an easily implemented feature that would resolve these issues and make the application "interesting" to long term locals:

The "Familiarity / Intimacy Scale"

Definition: An easily implemented V1 feature that suggests layers (and data points within them) based on user familiarity/intimacy with Huntsville. An experience level could be selected (novice, intermediate, advanced) and layers more associated with that experience level would be suggested. If toggled, the suggested layer(s) would display data points most relevant to location and/or layer subject as dictated by the experience level.

So there are two use cases:

A New Resident- user retention

The user would use the application to become familiar with the city (businesses, restaurants, infrastructure and recreation) and establish their patterns. Once the user's pattern has been established, maybe 3 months at most, the user has little incentive to use the application further and we lose that user. The user's incentive reduces further as the resident becomes increasingly familiar with the more dynamic aspects of the city (entertainment events, unofficial/seasonal sporting groups/activities, food deliveries/trucks...). The application would be more useful and longer-used if usefulness adapts to user familiarity with Huntsville. As in the second use case:

A Long Term Resident- very different needs

The user has lived in the city long enough to have no use for the more static layers. The initial appeal would be the layers that contain unobvious information (free wifi spots, bike racks, and swing dancing of course). This user has well established patterns and already knows where to look based on need. "I"m hungry; I already know the restaurants I enjoy eating at. I'll use urban spoon and develop tennis elbow if I'm looking for something new." However, this user knows there must be stuff out there the user is unaware of. "What's going on that I don't know about? What niche shop, restaurant or studio opened recently that I want to visit?"  

How the Familiarity/Intimacy Scale filters layers and points for users

Novice: Suggested layers include the basic utility layers and layers used to establish residency or basic needs. Business chains and largely static information would be heavily featured here.

Restaurants: Chains found almost everywhere (McDonalds, Olive Garden, Outback Stakehouse)

Recreation: Theater chains, Gym Chains, etc.

Stores: Common outlets such as Target, Walmart, Publix, Costco, and Sam's Club.

Intermediate: Suggested layers would include obvious features local to Huntsville with relatively static data.

Restaurants: Still include chain restaurants but perhaps not as common with well known local restaurants. "Rosie's"

Recreation: local well known small theaters, gyms, bars. "where the locals go"

Stores: local malls and shopping centers of all types. "specific needs: bike shops, artist shops, etc."

Advanced: Suggest layers would include esoteric and dynamic data points.

Restaurants: The authentic Japanese sushi restaurant that doesn't advertise. The food truck whose location isn't always well known or changes daily.

Recreation: Lowe Mill and all that happens there, local bands, obscure sporting groups

Stores: local independent businesses such as butchers, fresh seafood outlets, farmer's markets, local custom clothing stores.

This process only involves filtering data that we are already likely gathering. It would provide information that the user didn't know to search for and thus expose the user to new and hopefully interesting parts of the city automatically.

**Comment by spearna** [comment]
:+1:  @chrisbeaman

Also, here's a similar mobile apps to draw inspiration: 
http://mashable.com/2013/10/10/local-event-apps/

Especially the Gravy app.

**Comment by PaigeColburn** [comment]
Kyle, couldn't see the Imgur at work, but I love the Songza mood examples!!  

@spearna Yes, the Gravy example sounds very much like what you guys are trying to do. Additionally, I like some of the features of Now (pulling from so many sources) and LocalMind (asking locals or having locals do legwork with user generated info). 

James, I think the familiarity/intimacy scale, from the City's perspective, would make the App more useful to ALL our residents, not just visitors, and keep people using the app. This is good for sustainability. 

If the familiarity filter didn’t exist and I used this app and it suggested “Rosie’s” to me as a place to eat, I’d probably never use the app again. But if it tells me about “Happy Tummy” or some place more obscure and small, I’d be interested to explore that. So, I guess I'd be an "advanced" user of HSV.

**Comment by larrymason** [comment]
Daniel Tait brought up something from an outside conversation that might be worth considering... specifically Food truck operators could type an address (block/intersection) and see if that is a zone where there could setup for a while... and more in general, type in an address and see what the zone allows as far as a remodel, or new business (i.e. the zoning but not just the letter code rather an actual summary text of what is allowed)...

**Comment by kkoppineedi** [comment]
Great start on this project. I could not tell from the snapshots if the following layers were discussed:
- school zones
- constructions zones (long term road closures such as the bridge on Old Madison Pike)
- dog parks
- sub division boundaries (if data were to be available)

**Comment by mjcarroll** [comment]
I'm going to close this one, as this actually is a project now

:+1:
