### ISSUE TITLE
Code Licensing

### ISSUE THREAD

**Issue by dannagle** [Code4Huntsville/projects_leader_board#15]
Did we ever find out if the City of Huntsville / Madison County has code licensing restrictions? Have we decided on a license for the code we develop?

Some things to consider:
- Free GitHub hosting does not require an open source license. However, their free hosting requires that your code be publicly viewable. Because of this, most use an open source license.
- If we want to build an app for the iOS App Store, we cannot use code that is GPL. It is incompatible with their terms of service. I know of at least one case of app removal due to GPL.
- Google Play Store is GPL compatible.
- If we build a desktop app, any standard open source license (GPL, MIT, Apache) is usually OK, but their IT department will need to approve it. Whatever mechanism is needed to talk to their database could have particular restrictions.

**Comment by PaigeColburn** [comment]
When I forwarded this around, the reply I got was: 

"At this time, it has not been decided where the data will be housed.  We have looked at one solution so far and we will look at another one this week.
We do know that the data will not be accessed directly. -Sandra"

I doubt this fully answers your question? I will keep digging, if necessary.

**Comment by dannagle** [comment]
Since we are developing and hosting "Frontier App" ourselves, this question does not really matter anymore. We can license the code as we see fit. 

It'd be good to know for future projects though, but it is not pressing.
