### ISSUE TITLE
Animal Control, shelter application

### ISSUE THREAD

**Issue by larrymason** [Code4Huntsville/projects_leader_board#2]
The Huntsville Animal Shelter information and lost pet alert app.

The Huntsville Animal Shelter could possible use a tablet and browser-based application that:
- Allowed animal control officers to easily add information and photos of animals being processed into the shelter
- The information would be part of a database that was accessed by mobile devices and desktop browsers that would have sorting and filter algorithms so that anyone looking for a lost pet could use an intuitive search process
- Citizens could also enter details about lost pets, breed, color, size and photos that would be access by animal control officers are the time of the encounter such that if the animal could be identified it could be returned to the owner without having to process the animal into the shelter.

**Comment by larrymason** [comment]
According to the meeting last night, the city of Huntsville might be happy with the app as it is, so more research is needed to see if this is a candidate project

**Comment by mjcarroll** [comment]
Here is the link to the city app: http://maps.huntsvilleal.gov/lostanimals/

It uses the GIS department and the animal services IT infrastructure to plot lost animals on the city map.
