### ISSUE TITLE
EatHSV

### ISSUE THREAD

**Issue by mjcarroll** [Code4Huntsville/projects_leader_board#7]
## Elevator Pitch:

Build a webapp that allows users to look up health scores for restaurants in their vicinity.  Also view historical food safety ratings for restaurants.
## Data Source:

Alabama Department of Public Health: http://www.adph.org/foodscores/
### Example Entry:

```
Establishment Name: PHIL SANDOVAL'S MEXICAN RESTAURANTE
Address: 6125 University Dr
City: HUNTSVILLE
Zip Code: 35806
Score: 98
Smoke Free: Yes
Inspection date: 1/21/2015
```
## Tasks:
- Automated script for scraping health score data for Madison county
  - Geocoding addresses (leverage work from madisoncrimes repo)
  - Insert into backend database
- Frontend (Google Maps/OSM interface)

**Comment by mjcarroll** [comment]
:+1:

**Comment by larrymason** [comment]
Like it...

**Comment by mjcarroll** [comment]
So Yelp has an official schema for this: http://www.yelp.com/healthscores#businesses It will then be integrated into the Yelp reviews for the restaurants around the city.

Getting it in this format may be a good first effort.  If we want to do our own app or visualization, that would be the icing.

**Comment by spearna** [comment]
:+1:

**Comment by rickytherhino** [comment]
Yeah this is pretty sweet!

**Comment by mjcarroll** [comment]
I'm going to close this, as it is a project now:

http://github.com/mjcarroll/adph_lives
